/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new EmployeeManipulatorImpl().getEmployeeList().stream().forEachOrdered(employee -> System.out.println(employee.getName()));
    }
}
